"""Add card_id to loans

Revision ID: 33ef63b53fce
Revises: 783cb9dd58ca
Create Date: 2026-03-17 20:44:07.183787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ef63b53fce'
down_revision: Union[str, Sequence[str], None] = '783cb9dd58ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_loans_card_id', 'cards', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_loans_card_id', type_='foreignkey')
        batch_op.drop_column('card_id')
    # ### end Alembic commands ###
