"""Add created_at to cash_flows

Revision ID: 783cb9dd58ca
Revises: d9f57dacc55a
Create Date: 2026-03-17 14:45:01.282725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783cb9dd58ca'
down_revision: Union[str, Sequence[str], None] = 'd9f57dacc55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
