"""Add card_id to cashflows

Revision ID: d9f57dacc55a
Revises: 7e5656331b15
Create Date: 2026-03-17 14:29:07.540962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f57dacc55a'
down_revision: Union[str, Sequence[str], None] = '7e5656331b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_cashflows_card_id', 'cards', ['card_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cashflows_card_id', type_='foreignkey')
        batch_op.drop_column('card_id')

    # ### end Alembic commands ###
